/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * PDVNow API
 * OpenAPI spec version: v1
 */
import * as axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

export interface AuthResponse {
    userId?: string;
    /** @nullable */
    username?: string | null;
    /** @nullable */
    userType?: string | null;
    /** @nullable */
    accessToken?: string | null;
    accessTokenExpiresAtUtc?: string;
    /** @nullable */
    refreshToken?: string | null;
    refreshTokenExpiresAtUtc?: string;
}

export interface CreateProductRequest {
    /** @nullable */
    name?: string | null;
    /** @nullable */
    description?: string | null;
    /** @nullable */
    sku?: string | null;
    /** @nullable */
    barcode?: string | null;
    /** @nullable */
    unit?: string | null;
    costPrice?: number;
    salePrice?: number;
    stockQuantity?: number;
    /** @nullable */
    minStockQuantity?: number | null;
    /** @nullable */
    supplierId?: string | null;
}

export interface CreateSupplierRequest {
    /** @nullable */
    name?: string | null;
    /** @nullable */
    tradeName?: string | null;
    /** @nullable */
    cnpj?: string | null;
    /** @nullable */
    stateRegistration?: string | null;
    /** @nullable */
    email?: string | null;
    /** @nullable */
    phone?: string | null;
    /** @nullable */
    addressLine1?: string | null;
    /** @nullable */
    city?: string | null;
    /** @nullable */
    state?: string | null;
    /** @nullable */
    postalCode?: string | null;
}

export interface LoginRequest {
    /** @nullable */
    username?: string | null;
    /** @nullable */
    password?: string | null;
}

export interface ProductResponse {
    id?: string;
    /** @nullable */
    name?: string | null;
    /** @nullable */
    description?: string | null;
    /** @nullable */
    sku?: string | null;
    /** @nullable */
    barcode?: string | null;
    /** @nullable */
    unit?: string | null;
    costPrice?: number;
    salePrice?: number;
    stockQuantity?: number;
    /** @nullable */
    minStockQuantity?: number | null;
    isActive?: boolean;
    /** @nullable */
    supplierId?: string | null;
    createdAtUtc?: string;
    /** @nullable */
    updatedAtUtc?: string | null;
}

export interface RefreshRequest {
    userId?: string;
    /** @nullable */
    refreshToken?: string | null;
}

export interface SupplierResponse {
    id?: string;
    /** @nullable */
    name?: string | null;
    /** @nullable */
    tradeName?: string | null;
    /** @nullable */
    cnpj?: string | null;
    /** @nullable */
    stateRegistration?: string | null;
    /** @nullable */
    email?: string | null;
    /** @nullable */
    phone?: string | null;
    /** @nullable */
    addressLine1?: string | null;
    /** @nullable */
    city?: string | null;
    /** @nullable */
    state?: string | null;
    /** @nullable */
    postalCode?: string | null;
    isActive?: boolean;
    createdAtUtc?: string;
    /** @nullable */
    updatedAtUtc?: string | null;
}

export interface UpdateProductRequest {
    /** @nullable */
    name?: string | null;
    /** @nullable */
    description?: string | null;
    /** @nullable */
    sku?: string | null;
    /** @nullable */
    barcode?: string | null;
    /** @nullable */
    unit?: string | null;
    costPrice?: number;
    salePrice?: number;
    stockQuantity?: number;
    /** @nullable */
    minStockQuantity?: number | null;
    isActive?: boolean;
    /** @nullable */
    supplierId?: string | null;
}

export interface UpdateSupplierRequest {
    /** @nullable */
    name?: string | null;
    /** @nullable */
    tradeName?: string | null;
    /** @nullable */
    cnpj?: string | null;
    /** @nullable */
    stateRegistration?: string | null;
    /** @nullable */
    email?: string | null;
    /** @nullable */
    phone?: string | null;
    /** @nullable */
    addressLine1?: string | null;
    /** @nullable */
    city?: string | null;
    /** @nullable */
    state?: string | null;
    /** @nullable */
    postalCode?: string | null;
    isActive?: boolean;
}

export type GetApiV1ProductsParams = {
    query?: string;
    sku?: string;
    barcode?: string;
    active?: boolean;
    skip?: number;
    take?: number;
};

export type GetApiV1SuppliersParams = {
    query?: string;
    skip?: number;
    take?: number;
};

export const getPDVNowAPI = () => {
    const postApiV1AuthLogin = <TData = AxiosResponse<AuthResponse>>(loginRequest: LoginRequest, options?: AxiosRequestConfig): Promise<TData> => {
        return axios.default.post(`/api/v1/auth/login`, loginRequest, options);
    };

    const postApiV1AuthRefresh = <TData = AxiosResponse<AuthResponse>>(refreshRequest: RefreshRequest, options?: AxiosRequestConfig): Promise<TData> => {
        return axios.default.post(`/api/v1/auth/refresh`, refreshRequest, options);
    };

    const getApiV1Products = <TData = AxiosResponse<ProductResponse[]>>(params?: GetApiV1ProductsParams, options?: AxiosRequestConfig): Promise<TData> => {
        return axios.default.get(`/api/v1/products`, {
            responseType: "text",
            ...options,
            params: { ...params, ...options?.params },
        });
    };

    const postApiV1Products = <TData = AxiosResponse<ProductResponse>>(
        createProductRequest: CreateProductRequest,
        options?: AxiosRequestConfig
    ): Promise<TData> => {
        return axios.default.post(`/api/v1/products`, createProductRequest, options);
    };

    const getApiV1ProductsId = <TData = AxiosResponse<ProductResponse>>(id: string, options?: AxiosRequestConfig): Promise<TData> => {
        return axios.default.get(`/api/v1/products/${id}`, options);
    };

    const putApiV1ProductsId = <TData = AxiosResponse<ProductResponse>>(
        id: string,
        updateProductRequest: UpdateProductRequest,
        options?: AxiosRequestConfig
    ): Promise<TData> => {
        return axios.default.put(`/api/v1/products/${id}`, updateProductRequest, options);
    };

    const deleteApiV1ProductsId = <TData = AxiosResponse<void>>(id: string, options?: AxiosRequestConfig): Promise<TData> => {
        return axios.default.delete(`/api/v1/products/${id}`, options);
    };

    const getApiV1Suppliers = <TData = AxiosResponse<SupplierResponse[]>>(params?: GetApiV1SuppliersParams, options?: AxiosRequestConfig): Promise<TData> => {
        return axios.default.get(`/api/v1/suppliers`, {
            responseType: "text",
            ...options,
            params: { ...params, ...options?.params },
        });
    };

    const postApiV1Suppliers = <TData = AxiosResponse<SupplierResponse>>(
        createSupplierRequest: CreateSupplierRequest,
        options?: AxiosRequestConfig
    ): Promise<TData> => {
        return axios.default.post(`/api/v1/suppliers`, createSupplierRequest, options);
    };

    const getApiV1SuppliersId = <TData = AxiosResponse<SupplierResponse>>(id: string, options?: AxiosRequestConfig): Promise<TData> => {
        return axios.default.get(`/api/v1/suppliers/${id}`, options);
    };

    const putApiV1SuppliersId = <TData = AxiosResponse<SupplierResponse>>(
        id: string,
        updateSupplierRequest: UpdateSupplierRequest,
        options?: AxiosRequestConfig
    ): Promise<TData> => {
        return axios.default.put(`/api/v1/suppliers/${id}`, updateSupplierRequest, options);
    };

    const deleteApiV1SuppliersId = <TData = AxiosResponse<void>>(id: string, options?: AxiosRequestConfig): Promise<TData> => {
        return axios.default.delete(`/api/v1/suppliers/${id}`, options);
    };

    return {
        postApiV1AuthLogin,
        postApiV1AuthRefresh,
        getApiV1Products,
        postApiV1Products,
        getApiV1ProductsId,
        putApiV1ProductsId,
        deleteApiV1ProductsId,
        getApiV1Suppliers,
        postApiV1Suppliers,
        getApiV1SuppliersId,
        putApiV1SuppliersId,
        deleteApiV1SuppliersId,
    };
};
export type PostApiV1AuthLoginResult = AxiosResponse<AuthResponse>;
export type PostApiV1AuthRefreshResult = AxiosResponse<AuthResponse>;
export type GetApiV1ProductsResult = AxiosResponse<ProductResponse[]>;
export type PostApiV1ProductsResult = AxiosResponse<ProductResponse>;
export type GetApiV1ProductsIdResult = AxiosResponse<ProductResponse>;
export type PutApiV1ProductsIdResult = AxiosResponse<ProductResponse>;
export type DeleteApiV1ProductsIdResult = AxiosResponse<void>;
export type GetApiV1SuppliersResult = AxiosResponse<SupplierResponse[]>;
export type PostApiV1SuppliersResult = AxiosResponse<SupplierResponse>;
export type GetApiV1SuppliersIdResult = AxiosResponse<SupplierResponse>;
export type PutApiV1SuppliersIdResult = AxiosResponse<SupplierResponse>;
export type DeleteApiV1SuppliersIdResult = AxiosResponse<void>;
